# Generated by Django 3.2.2 on 2021-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(default='unnamed', max_length=255)),
                ('image_url', models.ImageField(upload_to='images')),
            ],
        ),
    ]
